### PR TITLE
fixes regression of imageSubFilter

### LINKED ISSUE #272: Regression for imagefilter in current dev
The latest merged PR #255 (specifically ff84e75) seemed to have caused a regression for the `imagefilter` functionality.
Opening a project with `imagefilter` set throws:
```
java.lang.NullPointerException
        at de.uniwue.web.io.FileDatabase.readBook(FileDatabase.java:386)
        at de.uniwue.web.io.FileDatabase.getBook(FileDatabase.java:216)
        at de.uniwue.web.controller.ViewerController.direct(ViewerController.java:271)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:890)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by chaddy314**
- moves processing of SubExtensionFilter to request processing
- switching between SubExtensions is now possible even if no SubExtensionFilter is set
- pagexml from mets projects can now switch between images described under Page::imageFilename and AlternativeImage::filename
- fixes #272

### CODE REVIEW

File: src/main/java/de/uniwue/web/controller/FileController.java [hunk 1]
```diff
@@ -126,20 +126,15 @@ private void init() {
...
 				List<String> foundImages = new LinkedList<>();
-				Map<String, String> localImageMap = fileManager.getLocalImageMap();
-				for ( String ext: supportedImageExt) {
-					String imgWithExt = new File(image).getName() + ext;
-					if(localImageMap.containsKey(imgWithExt)) {
-						foundImages.add(localImageMap.get(imgWithExt));
-					}
-				}
+				Map<String, List<String>> localImageMap = fileManager.getLocalImageMap();
 				if(foundImages.size() == 0) {
```
Comment (maxnth) [inline src/main/java/de/uniwue/web/controller/FileController.java:131]: In the refactored code `foundImages` will always have a size of `0` at this point. Can be removed.

File: src/main/java/de/uniwue/web/controller/LibraryController.java [hunk 2]
```diff
@@ -161,21 +161,45 @@ public String home(Model model) throws IOException {
...
+			}
+			if(!images.isEmpty()) {
+				if(fileMap.containsKey(currentFileName)) {
+					images.addAll(fileMap.get(currentFileName));
+					fileMap.put(currentFileName,images);
+				} else {
+					fileMap.put(currentFileName,images);
 				}
+				images.sort(Comparator.naturalOrder());
+				fileMap.put(currentFileName,images);
```
Comment (maxnth) [inline src/main/java/de/uniwue/web/controller/LibraryController.java:202]: `fileMap.put(currentFileName,images);` will get run in all cases so it can be extracted and `else` removed:
```Java
if(fileMap.containsKey(currentFileName)) {
	images.addAll(fileMap.get(currentFileName));
}
fileMap.put(currentFileName,images);
images.sort(Comparator.naturalOrder());
fileMap.put(currentFileName,images);
```

Comment (chaddy314) [reply src/main/java/de/uniwue/web/controller/LibraryController.java]: removed with [c296372 ](https://github.com/OCR4all/LAREX/pull/273/commits/c296372516aa9146ecaf5f7f8d27d9454516bca4)

File: src/main/java/de/uniwue/web/controller/FileController.java (hunk 1 above)
Comment (chaddy314) [reply src/main/java/de/uniwue/web/controller/FileController.java]: removed with [f0680c1 ](https://github.com/OCR4all/LAREX/pull/273/commits/f0680c1c93de14cef36e45eeeb7901284530f72c)
